### ISSUE TITLE
npm package ownership request

### ISSUE THREAD

**Issue by pladaria** [fdaciuk/react-lazy-img#1]
Hi,

I'm writing a react lazy img library (yet another one). I wanted to name it `react-lazy-img` but I see this name is already taken by your library

Is this project abandoned?

* [published version](https://www.npmjs.com/package/react-lazy-img) in `npm` is 0.0.0 (published a year ago)
* it has 0 weekly downloads and 0 projects depending on it
* looking at the source, this isn't really a lazy img loader (it just listens the load event)

So, if you don't plan any maintenance, would you consider transferring the ownership of the npm package name?

Best regards

**Comment by fdaciuk** [comment]
Hi @pladaria! It's done =)

This lib is not abandoned, but I didn't anything with it yet =)
But no problem, I can use that name inside my namespace for this library (like `@fdaciuk/react-lazy-img`) =)

Cheers! =)

**Comment by pladaria** [comment]
Thank you so much! 
I'll try to have the lib ready for this weekend. Of course I will credit you.
